version: "3.8"

services:
  nestapp:
    image: alejandro2314/e_comerce_m4:latest
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata:
